shona_dict = {
    # GREETINGS & POLITE EXPRESSIONS 
    "Hello": "Mhoroi",
    "Hi": "Mhoro",
    "Hey": "Mhoro",
    "Good morning": "Mangwanani",
    "Good morning my friend": "Mangwanani shamwari yangu",
    "Good morning everyone": "Mangwanani mose",
    "Good morning teacher": "Mangwanani mudzidzisi",
    "Good afternoon": "Masikati",
    "Good afternoon my friend": "Masikati shamwari yangu",
    "Good afternoon everyone": "Masikati mose",
    "Good evening": "Manheru",
    "Good evening my friend": "Manheru shamwari yangu",
    "Good evening everyone": "Manheru mose",
    "Good night": "Murare mushe",
    "Goodbye": "Musare mushe",
    "See you later": "Tozoonana gare gare",
    "See you tomorrow": "Tozoonana mangwana",
    "See you soon": "Toonana manje manje",
    "Take care": "Zvichengetedze",
    "Have a nice day": "Uve nezuva rakanaka",
    "How are you?": "Wakadini?",
    "How are you today?": "Wakadini nhasi?",
    "How are you my friend?": "Wakadini shamwari yangu?",
    "How are you doing?": "Wakadini?",
    "How is life?": "Hurisei hupenyu?",
    "How is everything?": "Zvinhu zvese zvirisei?",
    "I am fine": "Ndiri bhoo",
    "I am fine, thank you": "Ndiri bhoo, ndatenda",
    "I am good": "Ndiri bhoo",
    "I am okay": "Ndiri nani",
    "I am not okay": "Handisi nani",
    "I am well": "Zvinhu zvakanaka",
    "I am very well": "Zvinhu zvakanaka zvikuru",
    "And you?": "Nemiwo?",
    "Thank you": "Ndinokutendai",
    "Thank you very much": "Ndinotenda zvikuru",
    "Thanks a lot": "Ndatenda zvikuru",
    "Thanks": "Ndatenda",
    "You're welcome": "Muchitendei",
    "Please": "Ndinokumbirawo",
    "Excuse me": "Pamusoroi",
    "Sorry": "Ndine urombo",
    "I am sorry": "Ndine urombo",
    "I am sorry my friend": "Ndine urombo shamwari yangu",
    "No problem": "Hapana zvinonetsa",
    "It's okay": "Zvakanaka",
    "No worries": "Usazvinetse",
    "Bless you": "Mwari akuropafadze",
    "Congratulations": "Makorokoto",
    "Good luck": "Muve nerombo rakanaka",
    "Well done": "Waita zvakanaka",

    # INTRODUCTIONS & PERSONAL INFO
    "What is your name?": "Unonzani?",
    "My name is John": "Zita rangu ndinonzi John",
    "My name is Mary": "Zita rangu ndinonzi Mary",
    "My name is Alex": "Zita rangu ndinonzi Alex",
    "My name is Sarah": "Zita rangu ndinonzi Sarah",
    "My name is David": "Zita rangu ndinonzi David",
    "My name is Tinashe": "Zita rangu ndinonzi Tinashe",
    "My name is Tariro": "Zita rangu ndinonzi Tariro",
    "My name is Nyasha": "Zita rangu ndinonzi Nyasha",
    "My name is Simba": "Zita rangu ndinonzi Simba",
    "My name is Chipo": "Zita rangu ndinonzi Chipo",
    "My name is Tanaka": "Zita rangu ndinonzi Tanaka",
    "My name is Rudo": "Zita rangu ndinonzi Rudo",
    "My name is Farai": "Zita rangu ndinonzi Farai",
    "My name is Kudzai": "Zita rangu ndinonzi Kudzai",
    "Nice to meet you": "Ndinofara kukuziva",
    "Pleased to meet you": "Ndinofara kusangana nemi",
    "Where are you from?": "Unobva kupi?",
    "I am from Zimbabwe": "Ndinobva kuZimbabwe",
    "I am from Harare": "Ndinobva kuHarare",
    "I am from Bulawayo": "Ndinobva kuBulawayo",
    "I am from Mutare": "Ndinobva kwaMutare",
    "I am from Gweru": "Ndinobva kuGweru",
    "I am from Kwekwe": "Ndinobva kuKwekwe",
    "I am from Masvingo": "Ndinobva kuMasvingo",
    "I am from Zvishavane": "Ndinobva kuZvishavane",
    "How old are you?": "Une makore mangani?",
    "I am 18 years old": "Ndine makore gumi nemasere",
    "I am 19 years old": "Ndine makore gumi nemapfumbamwe",
    "I am 20 years old": "Ndine makore makumi maviri",
    "I am 21 years old": "Ndine makore makumi maviri nerimwe",
    "I am 22 years old": "Ndine makore makumi maviri nemaviri",
    "I am 23 years old": "Ndine makore makumi maviri nematatu",
    "I am 24 years old": "Ndine makore makumi maviri nemana",
    "I am 25 years old": "Ndine makore makumi maviri nemashanu",
    "What do you do?": "Unoitei?",
    "I am a student": "Ndiri mudzidzi",
    "I am a teacher": "Ndiri mudzidzisi",
    "I am a doctor": "Ndiri chiremba",
    "I am a nurse": "Ndiri mukoti",
    "I am an engineer": "Ndiri injiniya",
    "I am a farmer": "Ndiri murimi",
    "I am a driver": "Ndiri mutyairi",
    "I am a businessman": "Ndiri muzvinabhizimisi",
    "I am a housewife": "Ndiri mai veimba",
    "I am retired": "Ndiri pamudyandigere",
    "I am unemployed": "Handina basa",
    "Where do you live?": "Unogara kupi?",
    "I live in Harare": "Ndinogara kuHarare",
    "I live near the school": "Ndinogara pedyo nechikoro",
    "I live with my family": "Ndinogara nemhuri yangu",

    # FAMILY & RELATIONSHIPS 
    "Family": "Mhuri",
    "Mother": "Amai",
    "Father": "Baba",
    "Parents": "Vabereki",
    "Sister": "Sisi",
    "Brother": "Mukoma",
    "Older sister": "Sisi",
    "Older brother": "Mukoma",
    "Grandmother": "Mbuya",
    "Grandfather": "Sekuru",
    "Aunt": "Tete",
    "Uncle": "Sekuru",
    "Cousin": "Hama",
    "Niece": "Muzukuru",
    "Nephew": "Muzukuru",
    "Wife": "Mudzimai",
    "Husband": "Murume",
    "Child": "Mwana",
    "Children": "Vana",
    "Son": "Mwanakomana",
    "Daughter": "Mwanasikana",
    "Grandchild": "Muzukuru",
    "Friend": "Shamwari",
    "Boyfriend": "Mukomana",
    "Girlfriend": "Musikana",
    "Neighbour": "Muvakidzani",
    "Orphan": "Nherera",
    "Twin": "Mapatya",
    "Infant": "Mucheche",
    "Teenager": "Pwere",
    "Adult": "Munhu mukuru",
    "Elder": "Munhu anoremekedzwa",
    "Ancestor": "Madzitateguru",
    "Marriage": "Muchato",
    "Wedding": "Muchato",
    "Divorce": "Kurambana",
    "Engagement": "Kupfimbana",
    "Relative": "Hama",
    "Widow": "Shirikadzi",


    # COMMON VERBS & ACTIONS 
    "Go": "Enda",
    "Come": "Huya",
    "Come here": "Huya pano",
    "Come here please": "Ndinokumbira uuye pano",
    "Go there": "Enda uko",
    "Sit down": "Gara pasi",
    "Stand up": "Simuka",
    "Wait here": "Mira pano",
    "Listen": "Teerera",
    "Listen to me": "Nditerere",
    "Speak": "Taura",
    "Speak slowly": "Taura zvishoma nezvishoma",
    "Say it again": "Taura zvakare",
    "Repeat": "Dzokorora",
    "Repeat that": "Dzokorora izvozvo",
    "Repeat after me": "Dzokorora shure kwangu",
    "Run": "Mhanya",
    "Walk": "Famba",
    "Eat": "Idya",
    "Drink": "Inwa",
    "Sleep": "Rara",
    "Wake up": "Muka",
    "Work": "Shanda",
    "Play": "Tamba",
    "Read": "Verenga",
    "Write": "Nyora",
    "Learn": "Dzidza",
    "Teach": "Dzidzisa",
    "Help": "Batsira",
    "Help me please": "Ndibatsire ndapota",
    "Can you help me?": "Ungandibatsira here?",
    "Buy": "Tenga",
    "Sell": "Tengesa",
    "Pay": "Bhadhara",
    "Give": "Ndipowo",
    "Take": "Tora",
    "Bring": "Uya ne",
    "Carry": "Takura",
    "Open": "Vhura",
    "Close": "Vhara",
    "Enter": "Pinda",
    "Exit": "Buda",
    "Push": "Sunda",
    "Pull": "Dhonza",
    "Lift": "Simudza",
    "Drop": "Donhedza",
    "Break": "Tyora",
    "Fix": "Gadzirisa",
    "Clean": "Chenesa",
    "Cook": "Bika",
    "Wash": "Geza",
    "Dry": "Omisa",
    "Fold": "Peta",
    "Iron": "Ayina",
    "Sweep": "Tsvaira",
    "Wipe": "Pukuta",
    "Mop": "Korobha",
    "Water plants": "Diridza zvirimwa",
    "Feed animals": "Dyisa mhuka",
    "Drive": "Tyaira",
    "Fly": "Bhururuka",
    "Swim": "Tuhwina",
    "Climb": "Kwira",
    "Descend": "Buruka",
    "Laugh": "Seka",
    "Cry": "Chema",
    "Shout": "Shevedzera",
    "Whisper": "Nyereveza",
    "Think": "Funga",
    "Remember": "Rangarira",
    "Forget": "Kanganwa",
    "Know": "Ziva",
    "Understand": "Nzwisisa",
    "Do you understand?": "Unonzwisisa here?",
    "I understand": "Ndinonzwisisa",
    "I do not understand": "Handinzwisisi",
    "Explain": "Tsanangura",
    "Show me": "Ndiratidze",
    "Ask": "Bvunza",
    "Answer": "Pindura",
    "Call": "Fona",
    "Wait": "Mirira",
    "Stop": "Mira",
    "Start": "Tanga",
    "Finish": "Pedza",
    "Continue": "Enderera",
    "Change": "Chinja",
    "Choose": "Sarudza",
    "Find": "Tsvaga",
    "Lose": "Rasa",
    "Keep": "Chengeta",
    "Need": "Ndinoda",
    "Want": "Ndinoda",
    "Like": "Farira",
    "Love": "Rudo",
    "Hate": "Venga",
    "Hope": "Tarisira",
    "Believe": "Tenda",
    "Pray": "Namata",
    "Forgive": "Ruregerero",

    # ADJECTIVES & DESCRIPTIONS 
    "Good": "Zvakanaka",
    "Bad": "Zvakaipa",
    "Big": "Huru",
    "Small": "Diki",
    "Tall": "Refu",
    "Short": "Pfupi",
    "Wide": "Fara",
    "Narrow": "Dete",
    "Heavy": "Rema",
    "Light": "Reruka",
    "Fast": "Kukurumidza",
    "Slow": "Nonoka",
    "Hot": "Pisa",
    "Cold": "Tonhora",
    "Warm": "Dziya",
    "Cool": "Tonhorera",
    "New": "Itsva",
    "Old": "Tsaru",
    "Young": "Mudiki",
    "Clean": "Yakachena",
    "Dirty": "Yakasviba",
    "Empty": "Isina chinhu",
    "Full": "Izere",
    "Strong": "Simba",
    "Weak": "Isina simba",
    "Rich": "Mupfumi",
    "Poor": "Murombo",
    "Happy": "Kufara",
    "Sad": "Kusuruvara",
    "Angry": "Kutsamwa",
    "Afraid": "Kutya",
    "Surprised": "Kushamiswa",
    "Tired": "Kuneta",
    "Hungry": "Nzara",
    "Thirsty": "Nyota",
    "Sick": "Kurwara",
    "Healthy": "Kusimba",
    "Beautiful": "Kunaka",
    "Ugly": "Kushata",
    "Expensive": "Kudhura",
    "Cheap": "Kuchipa",
    "Easy": "Nyore",
    "Difficult": "Kuoma",
    "Important": "Kukosha",
    "Necessary": "Kufanira",
    "Possible": "Kugona",
    "Impossible": "Kusagona",
    "Right": "Kururama",
    "Wrong": "Kukanganisa",
    "Free": "Mahara",
    "Busy": "Kubatikana",
    "Lazy": "Nungo",
    "Hardworking": "Kushanda nesimba",
    "Honest": "Kuvimbika",
    "Dishonest": "Kusavimbika",
    "Brave": "Kusimba hana",
    "Cowardly": "Gwara",
    "Kind": "Mutsa",
    "Mean": "Hutsinye",
    "Patient": "Moyo murefu",
    "Impatient": "Moyo mupfupi",
    "Quiet": "Runyararo",
    "Noisy": "Ruzha",
    "Bright": "Chena",
    "Dark": "Rima",
    "Soft": "Nyoro",
    "Hard": "Nyara",
    "Smooth": "Chinyoro",
    "Rough": "Kuomarara",
    "Sweet": "Tapira",
    "Sour": "Vavira",
    "Bitter": "Unhuhwe",
    "Salty": "Zvinovava",
    "Spicy": "Zvinovavira",
    "Fresh": "Zvinyoto",
    "Rot": "Kuora",
    "Loud": "Kurira",
    "Faint": "Kupera simba",
    "Accurate": "Kururama",

    # NUMBERS 
    "One": "Poshi",
    "Two": "Piri",
    "Three": "Tatu",
    "Four": "Ina",
    "Five": "Shanu ",
    "Six": "Tanhatu",
    "Seven": "Nomwe",
    "Eight": "Sere",
    "Nine": "Pfumbamwe",
    "Ten": "Gumi",
    "Eleven": "Gumi nerimwe",
    "Twelve": "Gumi neviri",
    "Thirteen": "Gumi netatu",
    "Fourteen": "Gumi neina",
    "Fifteen": "Gumi neshanu",
    "Sixteen": "Gumi netanhatu",
    "Seventeen": "Gumi nenomwe",
    "Eighteen": "Gumi nesere",
    "Nineteen": "Gumi nepfumbamwe",
    "Twenty": "Makumi maviri",
    "Twenty-one": "Makumi maviri nerimwe",
    "Twenty-two": "Makumi maviri nemaviri",
    "Twenty-three": "Makumi maviri nematatu",
    "Twenty-four": "Makumi maviri nemana",
    "Twenty-five": "Makumi maviri nemashanu",
    "Thirty": "Makumi matatu",
    "Forty": "Makumi mana",
    "Fifty": "Makumi mashanu",
    "Sixty": "Makumi matanhatu",
    "Seventy": "Makumi manomwe",
    "Eighty": "Makumi masere",
    "Ninety": "Makumi mapfumbamwe",
    "One hundred": "Zana",
    "Two hundred": "Mazana maviri",
    "Five hundred": "Mazana mashanu",
    "One thousand": "Churu",
    "Ten thousand": "Zviuru gumi",
    "One hundred thousand": "Zana rezviuru",
    "One million": "Miriyoni",
    "1": "Poshi",
    "2": "Piri",
    "3": "Tatu",
    "4": "Ina",
    "5": "Shanu",
    "6": "Tanhatu",
    "7": "Nomwe",
    "8": "Sere",
    "9": "Pfumbamwe",
    "10": "Gumi",
    "11": "Gumi nerimwe",
    "12": "Gumi neviri",
    "13": "Gumi netatu",
    "14": "Gumi neina",
    "15": "Gumi neshanu",
    "16": "Gumi netanhatu",
    "17": "Gumi nenomwe",
    "18": "Gumi nesere",
    "19": "Gumi nepfumbamwe",
    "20": "Makumi maviri",
    "21": "Makumi maviri nerimwe",
    "22": "Makumi maviri nemaviri",
    "23": "Makumi maviri nematatu",
    "24": "Makumi maviri nemana",
    "25": "Makumi maviri nemashanu",
    "30": "Makumi matatu",
    "40": "Makumi mana",
    "50": "Makumi mashanu",
    "60": "Makumi matanhatu",
    "70": "Makumi manomwe",
    "80": "Makumi masere",
    "90": "Makumi mapfumbamwe",
    "100": "Zana",
    "200": "Mazana maviri",
    "500": "Mazana mashanu",
    "1000": "Churu",
    "10 000": "Zviuru gumi",
    "100 000": "Zana rezviuru",
    "1 000 000": "Miriyoni",
    "what is the Shona word for one": "Poshi",
    "what is the Shona word for two": "Piri",
    "what is the Shona word for three": "Tatu",
    "what is the Shona word for four": "Ina",
    "what is the Shona word for five": "Shanu",
    "how do you say one in Shona": "Poshi",
    "how do you say two in Shona": "Piri",
    "how do you say three in Shona": "Tatu",
    "how do you say four in Shona": "Ina",
    "how do you say five in Shona": "Shanu",
    "count from one to five": "Poshi, Piri, Tatu, Ina, Shanu",
    "count from 1 to 5": "Poshi, Piri, Tatu, Ina, Shanu",
    "numbers one to five": "Poshi, Piri, Tatu, Ina, Shanu",
    "numbers 1 to 5": "Poshi, Piri, Tatu, Ina, Shanu",
    "counting": "Kuverenga",
    "learn numbers": "Dzidza manhamba",

    # DAYS, MONTHS & TIME 
    "Today": "Nhasi",
    "Tomorrow": "Mangwana",
    "Yesterday": "Nezuro",
    "Day after tomorrow": "Kuswera mangwana",
    "Day before yesterday": "Kuswera nezuro",
    "Now": "izvezvi",
    "Then": "Ipapo",
    "Soon": "Manje manje",
    "Later": "Gare gare",
    "Immediately": "Pakarepo",
    "Morning": "Mangwanani",
    "Afternoon": "Masikati",
    "Evening": "Manheru",
    "Night": "Usiku",
    "Midnight": "Pakati pehusiku",
    "Dawn": "Mambakwedza",
    "Sunset": "Kuvira kwezuva",
    "Sunrise": "Kubuda kwezuva",
    "Monday": "Muvhuro",
    "Tuesday": "Chipiri",
    "Wednesday": "Chitatu",
    "Thursday": "China",
    "Friday": "Chishanu",
    "Saturday": "Mugovera",
    "Sunday": "Svondo",
    "Week": "Vhiki",
    "Weekend": "Kupera kwesvondo",
    "Month": "Mwedzi",
    "January": "Ndira",
    "February": "Kukadzi",
    "March": "Kurume",
    "April": "Kubvumbi",
    "May": "Chivabvu",
    "June": "Chikumi",
    "July": "Chikunguru",
    "August": "Nyamavhuvhu",
    "September": "Gunyana",
    "October": "Gumiguru",
    "November": "Mbudzi",
    "December": "Zvita",
    "Year": "Gore",
    "Season": "Mwaka",
    "Spring ": "Chirimo",
    "Summer": "Zhizha",
    "Autumn": "Matsutso",
    "Winter": "Chando",
    "Clock": "Chiringazuva",
    "What time is it?": "Inguvai?",
    "It is morning": "Mangwanani",
    "It is afternoon": "Masikati",
    "It is evening": "Manheru",
    "It is night": "Usiku",

    # QUESTIONS & QUESTION WORDS 
    "What?": "Chii?",
    "What is this?": "Chii ichi?",
    "What is that?": "Chii icho?",
    "Why?": "Sei?",
    "How?": "Sei?",
    "How much?": "Marii?",
    "How many?": "Vangani?",
    "Who?": "Ndiani?",
    "Whose?": "Chaani?",
    "Which?": "Chipi?",
    "Where?": "Kupi?",
    "When?": "Rinhi?",
    "Is it okay?": "Zvakanaka here?",
    "Are you sure?": "Une chokwadi here?",
    "Really?": "Chokwadi here?",
    "Are you ready?": "Wagadzirira here?",
    "Can I go?": "Ndinogona kuenda here?",
    "May I come in?": "Ndinogona kupinda here?",
    "Do you want?": "Unoda here?",
    "Do you like?": "Unofarira here?",
    "Do you know?": "Unoziva here?",
    "Do you speak Shona?": "Unotaura chiShona here?",
    "Do you understand?": "Unonzwisisa here?",
    "Can you repeat?": "Ungadzokorora here?",
    "Can you speak slowly?": "Ungataura zvishoma nezvishoma here?",
    "What did you say?": "Wati chii?",
    "What does it mean?": "Zvinorevei?",
    "How do you say X in Shona?": "Unotaura sei X neShona?",
    "Is that correct?": "Ndizvo here?",
    "Anything else?": "Pane chimwe here?",

    # COMMON NOUNS 
    "House": "Imba",
    "Room": "Kamuri",
    "Door": "Musuwo",
    "Window": "Hwindo",
    "Wall": "Rusvingo",
    "Floor": "Pasi",
    "Roof": "Denga (roof)",
    "Table": "Tafura",
    "Chair": "Chigaro",
    "Bed": "Mubhedha",
    "Pillow": "Mutsago",
    "Blanket": "Gumbeze",
    "Mat": "Mhetse",
    "Cupboard": "Kabati",
    "Kitchen": "Imba yekubikira",
    "Living room": "Imba yokutandarira",
    "Bedroom": "Imba yekurara",
    "Toilet": "Chimbuzi",
    "Bucket": "Mugomo",
    "Soap": "Sipo",
    "Towel": "Tauro",
    "Water": "Mvura",
    "Food": "Chikafu",
    "Drink": "Chinwiwa",
    "Bread": "Chingwa",
    "Rice": "Mupunga",
    "Maize meal": "Hupfu ",
    "Meat": "Nyama",
    "Chicken": "Huku",
    "Fish": "Hove",
    "Vegetables": "Muriwo",
    "Fruit": "Muchero",
    "Orange": "Ranjisi",
    "Banana": "Bhanana",
    "Sugar": "Shuga",
    "Salt": "Munyu",
    "Oil": "Mafuta",
    "Tea": "Svutugadzike",
    "Coffee": "Kofi",
    "Milk": "Mukaka",
    "Egg": "Zai",
    "Claypot": "Hari",
    "Pot": "Poto",
    "Knife": "Banga",
    "Fork": "Forogo",
    "Spoon": "Chipunu",
    "Plate": "Ndiro",
    "Cup": "Kapu",
    "Glass": "Girazi",
    "School": "Chikoro",
    "Classroom": "Kirasi",
    "Teacher": "Mudzidzisi",
    "Student": "Mudzidzi",
    "Pen": "Chinyoreso",
    "Pencil": "Penzura",
    "Book": "Bhuku",
    "Paper": "Bepa",
    "Bag": "Bhegi",
    "Backpack": "Chikwama",
    "Hospital": "Chipatara",
    "Doctor": "Chiremba",
    "Nurse": "Mukoti",
    "Medicine": "Mushonga",
    "Injection": "Jekiseni",
    "Bed": "Mubhedha",
    "Shop": "Chitoro",
    "Market": "Musika",
    "Money": "Mari",
    "Price": "Mutengo",
    "Receipt": "Risiti",
    "Church": "Chechi",
    "Temple": "Temberi",
    "Police station": "Kamba yeMapurisa",
    "Police officer": "Mupurisa",
    "Fire station": "Kamba yemoto",
    "Bank": "Bhangi",
    "Hotel": "Hotera",
    "Airport": "Nhandare yendege",
    "Bus station": "Chiteshi chebhazi",
    "Car": "Motokari",
    "Bicycle": "Bhasikoro",
    "Motorcycle": "Mudhudhudhu",
    "Bus": "Bhazi",
    "Train": "Chitima",
    "Plane": "Ndege",
    "Boat": "Chikepe",
    "Road": "Mugwagwa",
    "Bridge": "Zambuko",
    "Farm": "Purazi",
    "Field": "Munda",
    "Garden": "Bindu",
    "Forest": "Sango",
    "River": "Rwizi",
    "Lake": "Dhamu",
    "Mountain": "Gomo",
    "Hill": "Chikomo",
    "Valley": "Mupata",
    "Village": "Musha",
    "City": "Guta",
    "Town": "Taundi",
    "Country": "Nyika",

    # DIRECTIONS & LOCATIONS 
    "Where is the bathroom?": "Chimbuzi chiripi?",
    "Where is the school?": "Chikoro chiripi?",
    "Where is the market?": "Musika uripi?",
    "Where is the hospital?": "Chipatara chiripi?",
    "Where is the shop?": "Chitoro chiripi?",
    "Where are you going?": "Urikuenda kupi?",
    "I am going to Harare": "Ndiri kuenda kuHarare",
    "Come here": "Huya pano",
    "Go there": "Enda uko",
    "Left": "Ruboshwe",
    "Right": "Rudyi",
    "Near": "Pedyo",
    "Far": "Kure",
    "Behind": "Shure",
    "In front of": "Pamberi",
    "Next": "Pedyo",
    "Inside": "Mukati",
    "Outside": "Kunze",
    "Up": "Kumusoro",
    "Down": "Kuzasi",
    "North": "Maodzanyemba",
    "South": "Chamhembe",
    "East": "Mabvazuva",
    "West": "Madokero",
    "Address": "Kero",
    "Landmark": "Chiratidzo",
    "Crossroads": "Mharadzano",

    # FOOD & DRINK 
    "Breakfast": "Kudya kwemangwanani",
    "Lunch": "Kudya kwemasikati",
    "Dinner": "Kudya kwemanheru",
    "Fruit": "Muchero",
    "Vegetables": "Muriwo",
    "Corn": "Chibage",
    "Sadza": "Sadza",
    "Porridge": "Bota",
    "Stew": "Muto",
    "Grilled meat": "Nyama yakagochwa",
    "Fried meat": "Huku yakagochwa",
    "Roasted maize": "Chibage chakagochwa",
    "Peanuts": "Nzungu",
    "Cabbage": "Kabheji",
    "Onion": "Hanyanisi",
    "Tomato": "Madomasi",
    "Potato": "Mbatatisi",
    "Sweet potato": "Mbambaira",
    "Pumpkin": "Manhanga",
    "Cake": "Keke",
    "Honey": "Uchi",
    "Beer": "Doro",

    # SHOPPING & TRANSACTIONS 
    "How much is this?": "Ichi chinoita marii?",
    "It is expensive": "Chinodhura",
    "It is cheap": "Chakachipa",
    "I want to buy": "Ndinoda kutenga",
    "I am just looking": "Ndiri kungotarisa",
    "Do you have…?": "Mune…?",
    "Yes, we have": "Ehe, tine",
    "No, we don't have": "Kwete, hatina",
    "I will take it": "Ndichazvitora",
    "Here is the money": "Heino mari",
    "Too much": "Kunyanya",
    "Enough": "Zvakakwana",
    "Open": "Vhurwa",
    "Closed": "Vharwa",
    "Colour": "Ruvara",
    "Black": "Dema",
    "White": "Chena",
    "Red": "Tsvuku",

    # EMERGENCY & HEALTH
    "Help!": "Ndifambisei!",
    "Call the police": "Fonerai mapurisa",
    "I need a doctor": "Ndirikuda chiremba",
    "I am sick": "Ndiri kurwara",
    "I am injured": "Ndakuvara",
    "Where is the hospital?": "Chipatara chiripi?",
    "My head hurts": "Musoro wangu unorwadza",
    "My stomach hurts": "Dumbu rangu rinorwadza",
    "Cough": "Kukosora",
    "Flu": "Furuenza",
    "Medicine": "Mushonga",
    "Painkiller": "Mushonga unoderedza marwadzo",
    "Fire": "Moto",
    "Firefighter": "Mudzimamoto",
    "Accident": "Tsaona",
    "Danger": "Ngozi",
    "Safe": "Chengetedzeka",
    "Poison": "Chepfu",
    "Pregnant": "Ane pamuviri",
    "Childbirth": "Kusununguka",
    "Vaccination": "Jekiseni rekudzivirira",
    "Quarantine": "Kuparadzaniswa",

    # WEATHER & NATURE
    "Weather": "Mamiriro ekunze",
    "Sun": "Zuva",
    "Rain": "Mvura",
    "Rainy season": "Mwaka wekunaya",
    "Wind": "Mhepo",
    "Storm": "Dutu",
    "Thunder": "Kutinhira",
    "Lightning": "Mheni",
    "Cloud": "Gore",
    "Sky": "Denga",
    "Star": "Nyeredzi",
    "Moon": "Mwedzi",
    "Earth": "Nyika ",
    "Ground": "Pasi",
    "Sand": "Jecha",
    "Stone": "Dombo",
    "Soil": "Ivhu",
    "Grass": "Huswa",
    "Tree": "Muti",
    "Flower": "Ruva",
    "Leaf": "Shizha",
    "Seed": "Mbeu",
    "Root": "Midzi",
    "Animal": "Mhuka",
    "Bird": "Shiri",
    "Insect": "Zvipembenene",
    "Fish": "Hove",
    "Snake": "Nyoka",
    "Lion": "Shumba",
    "Elephant": "Nzou",
    "Giraffe": "Twiza",
    "Zebra": "Mbizi",
    "Monkey": "Tsoko",
    "Cow": "Mombe",
    "Goat": "Mbudzi",
    "Sheep": "Gwai",
    "Pig": "Nguruve",
    "Dog": "Imbwa",
    "Cat": "Katsi",
    "Chicken": "Huku",

    # WORK & PROFESSIONS 
    "Job": "Basa",
    "Work": "Basa",
    "Salary": "Muhoro",
    "Boss": "Sabhuku",
    "Employee": "Mushandi",
    "Colleague": "Mushandi pamwe",
    "Office": "Hofisi",
    "Meeting": "Musangano",
    "Interview": "Kubvunzurudza",
    "Business": "Bhizimusi",
    "Customer": "Mutengi",
    "Lawyer": "Gweta",
    "Judge": "Mutongi",
    "Police officer": "Mupurisa",
    "Soldier": "Soja",
    "Driver": "Mutyairi",
    "Pilot": "Mutyairi wendege",
    "Carpenter": "Muvezi",

    # EDUCATION & LEARNING 
    "School": "Chikoro",
    "University": "Yunivhesiti",
    "Subject": "Chidzidzo",
    "Lesson": "Chidzidzo",
    "Exam": "Bvunzo",
    "Test": "Bvunzo",
    "Pass": "Pasa",
    "Fail": "Kundikana",
    "Learn": "Dzidza",
    "Study": "Funda",
    "Teach": "Dzidzisa",
    "Understand": "Nzwisisa",
    "Knowledge": "Ruzivo",
    "Wisdom": "Uchenjeri",
    "Intelligence": "Hungwaru",
    "Memory": "Kurangarira",
    "Certificate": "Chitupa",
    "Teacher": "Mudzidzisi",

    # TRAVEL & TRANSPORTATION
    "Travel": "Kufamba",
    "Trip": "Rwendo",
    "Journey": "Rwendo",
    "Luggage": "Mutoro",
    "Ticket": "Tikiti",
    "Passport": "Pasipoti",
    "Airport": "Nhandare yendege",
    "Bus station": "Chiteshi chebhazi",
    "Train station": "Chiteshi chechitima",
    "Arrival": "Kusvika",
    "Departure": "Kubuda",
    "Boarding": "Kukwira",
    "Hotel": "Hotera",
    "Tourist": "Mushanyi",
    "Guide": "Mutungamiri",
    "Souvenir": "Chirangaridzo",
    "Beach": "Mahombekombe",
    "Mountain": "Gomo",
    "Waterfall": "Mapopoma",
    "And": "ne",

    # HOME & CHORES
    "Home": "Imba",
    "Living room": "Imba yokutandarira",
    "Bedroom": "Imba yekurara",
    "Kitchen": "Kichini",
    "Bathroom": "Chimbuzi",
    "Garden": "Bindu",
    "Yard": "Chivanze",
    "Fence": "Fenzi",
    "Gate": "Gedhi",
    "Roof": "Denga",
    "Floor": "Pasi",
    "Wall": "Rusvingo",
    "Window": "Hwindo",
    "Door": "Musuwo",
    "Key": "Kiyi",
    "Bed": "Mubhedha",
    "Pillow": "Mutsago",
    "Blanket": "Gumbeze",
    "Curtain": "Chidzitiro",
    "Lamp": "Rambi",
    "Light": "Chiedza",
    "Sweep": "Tsvaira",
    "Wash dishes": "Geza ndiro",
    "Laundry": "Kuwacha",
    "Garbage": "Marara",
    "Broom": "Mutsvairo",

    # CONVERSATION & SOCIAL 
    "Let's go": "Handeyi",
    "Wait for me": "Ndimirirei",
    "Come with me": "Huya neni",
    "I will come back": "Ndichadzoka",
    "Maybe": "Pamwe",
    "Of course": "Zvirokwazvo",
    "Certainly": "Zvirokwazvo",
    "Never mind": "Usazvinetse",
    "It doesn't matter": "Hazvina basa",
    "No way": "Hazvibviri",
    "I promise": "Ndinovimbisa",
    "Really?": "Chokwadi here?",
    "I think so": "Ndinofunga kudaro",
    "I don't think so": "Handifungi kudaro",
    "Tell me": "Ndiudze",
    "Show me": "Ndiratidze",
    "Let me see": "Ndione",
    "I don't know": "Handizivi",
    "I know": "Ndinoziva",
    "Maybe yes, maybe no": "Pamwe zvingaite pamwe zvingarege",
    "That's right": "Ndizvozvo",
    "That's wrong": "Hazvisirizvo",
    "Exactly": "Saiizvoizvo",
    "Probably": "Pamwe",
    "Sometimes": "Dzimwe nguva",
    "Always": "Nguva dzose",
    "Never": "Hazvifi zvakaita",
    "Usually": "Kazhinji",
    "Rarely": "Kashoma",
    "Often": "Kakawanda kacho",

    # COMPUTER & INTERNET 
    "Computer": "Kombiyuta",
    "Phone": "Runharembozha",

    # BODY PARTS 
    "Head": "Musoro",
    "Hair": "Bvudzi",
    "Eye": "Ziso",
    "Eyes": "Meso",
    "Ear": "Nzeve",
    "Nose": "Mhuno",
    "Mouth": "Muromo",
    "Tooth": "Zino",
    "Teeth": "Meno",
    "Tongue": "Rurimi",
    "Lip": "Muromo",
    "Neck": "Mutsipa",
    "Shoulder": "Bendekete",
    "Arm": "Ruoko",
    "Elbow": "Gokora",
    "Hand": "Ruoko",
    "Finger": "Chigunwe",
    "Chest": "Chipfuva",
    "Stomach": "Dumbu",
    "Back": "Musana",
    "Leg": "Gumbo",
    "Knee": "Ibvi",
    "Foot": "Tsoka",
    "Skin": "Ganda",
    "Bone": "Bvupa",
    "Blood": "Ropa",
    "Heart": "Moyo",
    "Lung": "Mapapu",

    # CLOTHING (731-755)
    "Clothes": "Mbatya",
    "Shirt": "Hembe",
    "Trousers": "Bhurugwa",
    "Jacket": "Bhachi",
    "Coat": "Jasi",
    "Sweater": "Juzi",
    "Underwear": "Mbatya dzemukati",
    "Socks": "Masokisi",
    "Shoes": "Shangu",
    "Hat": "Ngowani",
    "Cap": "Kepisi",
    "Belt": "Bhandi",
    "Tie": "Tai",
    "Glasses": "Magirazi",
    "Watch": "Wachi",
    "Necklace": "Chishongo",
    "Earrings": "Mhete dzenzeve",

    # EMOTIONS & FEELINGS 
    "Joy": "Mufaro",
    "Sadness": "Kusuwa",
    "Fear": "Kutya",
    "Anger": "Hasha",
    "Love": "Rudo",
    "Hate": "Ruvengo",
    "Peace": "Runyararo",
    "Worry": "Kunetseka",
    "Excitement": "Mufaro wakanyanya",
    "Boredom": "Kufinhwa",
    "Confusion": "Nyonganyonga",
    "Loneliness": "Kusurukirwa",
    "Hope": "Tarisiro",
    "Despair": "Kupererwa",
    "Courage": "Hushingi",
    "Jealousy": "Godo",
    "Gratitude": "Kutenda",
    "Shame": "Nyadzi",
    "Pride": "Kuzvikudza",
    "Calmness": "Kudzikama",
    "Dawn": "Mambakwedza",
    "Yesterday morning": "Mangwanani ezuro",
    "Tomorrow evening": "Manheru amangwana",
    "Last week": "Vhiki rapfuura",
    "Next month": "Mwedzi unouya",
    "This year": "Gore rino",

    # NATURE & ENVIRONMENT 
    "Ocean": "Gungwa",
    "Wave": "Masaisai",
    "Island": "Chitsuwa",
    "Cave": "Bako",
    "Cliff": "Mawere",
    "Desert": "Gwenga",
    "Grassland": "Bani",
    "Swamp": "Matoro",
    "Waterfall": "Mapopoma",
    "Earthquake": "Kudengenyeka kwenyika",
    "Flood": "Mafashamo",
    "Drought": "Kusanaya kwemvura",
    "Storm": "Dutu",
    "Lightning": "Mheni",
    "Thunder": "Kutinhira",
    "Rainbow": "Murarabungu",
    "Shadow": "Mumvuri",

    # ABSTRACT CONCEPTS 
    "Truth": "Chokwadi",
    "Lie": "Nhema",
    "Freedom": "Rusununguko",
    "Equality": "Kuenzana",
    "Respect": "Ruremekedzo",
    "Honour": "Kukudzwa",
    "Trust": "Kuvimba",
    "Loyalty": "Kuvimbika",
    "Patience": "Moyo murefu",
    "Generosity": "Rupo",
    "Greed": "Makaro",
    "Humility": "Kuzvininipisa",
    "Wisdom": "Uchenjeri",
    "Foolishness": "Hupenzi",
    "Strength": "Simba",
    "Weakness": "Utete",
    "Beauty": "Runako",
    "Ugliness": "Kushata",
    "Poverty": "Urombo",
    "Wealth": "Hupfumi", 
    "Television": "Chivhitivhiti",
    
    # SPORTS & LEISURE 
    "Football (soccer)": "Nhabvu",
    "Running": "Kumhanya",
    "Swimming": "Kutuhwina",
    "Cycling": "Kuchovha bhasikoro",
    "Exercise": "Kurovedza muviri",
    "Game": "Mutambo",
    "Team": "Chikwata",
    "Player": "Mutambi",
    "Goal": "Zvibodzwa",
    "Ball": "Bhora",
    "Stadium": "Nhandare",
    "Field": "Munda",
 
    # MUSIC & ARTS 
    "Song": "Rwiyo",
    "Music": "Mumhanzi",
    "Singer": "Muimbi",
    "Dance": "Kutamba",
    "Dancer": "Mutambi",
    "Drum": "Ngoma",
    "Guitar": "Gitare",
    "Flute": "Nyere",
    "Artist": "Munyori",
    "Colour": "Ruvara",

    # HEALTH & MEDICINE 
    "Virus": "Utachiona",
    "Pain": "Marwadzo",
    "Swelling": "Kuzvimba",
    "Bruise": "Ronda",


    # COMMUNICATION 
    "Letter": "Tsamba",
    "Phone call": "Kufona",
    "Video call": "Kufona nevhidhiyo",
    "Text": "Chinyorwa",
    "Chat": "Kutaura",
    "Conversation": "Nhaurirano",
    "Language": "Mutauro",
    "Translate": "Dudzira",
    "Meaning": "Zvinoreva",
    "Pronunciation": "Madudzirwo",
    "Vocabulary": "Mazwi",
    "Sentence": "Mutsara",
    "Word": "Shoko",
    "Phrase": "Chirevo",
    "Answer": "Mhinduro",

    # EMERGENCY & SAFETY 
    "Danger": "Ngozi",
    "Accident": "Tsaona",
    "Fire": "Moto",
    "Rescue": "Kununura",
    "Warning": "Yambiro",
    "Alert": "Yambiro",
    "Injury": "Kukuvara",
    "Bleeding": "Kubuda ropa",
    "Unconscious": "Afenda",
    "Robbery": "Kuba",
    "Violence": "Mhirizhonga",
    "War": "Hondo",
    "Peace": "Runyararo",

    # ADDITIONAL VERBS
    "Accept": "Gamuchira",
    "Refuse": "Ramba",
    "Allow": "Bvumira",
    "Forbid": "Rambidza",
    "Create": "Sika",
    "Destroy": "Paradza",
    "Build": "Vaka",
    "Repair": "Gadzirisa",
    "Improve": "Natsa",
    "Worsen": "Kuwedzera kuipa",
    "Grow": "Kura",
    "Shrink": "Deredzwa",
    "Increase": "Wedzera",
    "Decrease": "Deredza",
    "Connect": "Batanidza",
    "Disconnect": "Paradzanisa",
}

